# Test against LTS version of Node.js
environment:
  nodejs_version: "6"

# Install scripts (runs after repo cloning)
install:
  # Get the latest stable version of Node.js and NPM
  - ps: Install-Product node $env:nodejs_version
  - npm cache clear
  - npm i npm@latest -g
  # Install project specific modules
  - npm install -g eslint
  - npm install -g nyc
  - npm install -g mocha
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - eslint --version
  - nyc --version
  - mocha --version
  # lint and test
  - eslint .
  - mocha --reporter spec test
  - nyc npm test

# Don't actually build.
build: off
